import React, { useState, useCallback } from 'react';
import { generateImage } from '../services/geminiService';
import Spinner from './Spinner';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState<string>('A photorealistic image of a futuristic city at sunset, with flying cars.');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);

  const handleSubmit = useCallback(async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) {
      setError("Prompt cannot be empty.");
      return;
    }
    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
      const imageB64 = await generateImage(prompt);
      setGeneratedImage(`data:image/png;base64,${imageB64}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unknown error occurred.");
    } finally {
      setIsLoading(false);
    }
  }, [prompt]);

  return (
    <div className="space-y-6">
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label htmlFor="prompt-gen" className="block text-sm font-semibold mb-2" style={{ color: 'var(--color-text-dim)' }}>Image Description</label>
          <textarea
            id="prompt-gen"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., A majestic lion with a crown of stars"
            className="w-full bg-transparent border rounded-lg p-3 focus:outline-none focus:ring-2 focus:shadow-[var(--shadow-inner-sm)]"
            // FIX: Replaced invalid `ringColor` property with the correct CSS custom property `--tw-ring-color`
            // to align with Tailwind's ring utilities and resolve the TypeScript error.
            style={{ borderColor: 'var(--color-border)', color: 'var(--color-text)', '--tw-ring-color': 'var(--color-accent)' } as React.CSSProperties}
            rows={3}
          />
        </div>
        <button
          type="submit"
          disabled={isLoading}
          className="w-full flex justify-center items-center gap-2 font-bold py-3 px-4 border rounded-lg text-lg transition-all duration-300 disabled:opacity-50 disabled:cursor-wait hover:shadow-[var(--shadow-lg)] hover:-translate-y-0.5"
          style={{
            background: `linear-gradient(45deg, var(--color-accent), var(--color-accent-dark))`,
            color: '#FFFFFF',
            borderColor: 'transparent',
            opacity: isLoading ? 0.7 : 1,
          }}
        >
          {isLoading ? <><Spinner /> Generating...</> : 'Generate Image'}
        </button>
      </form>

      {error && <div className="text-red-500 border border-red-500 bg-red-500/10 p-3 text-center rounded-lg">{error}</div>}

      <div className="flex justify-center items-center p-4 border rounded-lg min-h-[400px]" style={{ borderColor: 'var(--color-border)' }}>
        {isLoading && <div className="text-center flex flex-col items-center gap-4" style={{ color: 'var(--color-text-dim)' }}><Spinner /><span>Generating your image... This might take a moment.</span></div>}
        {!isLoading && !generatedImage && <div style={{ color: 'var(--color-text-dim)' }}>Your generated image will appear here.</div>}
        {generatedImage && (
          <img src={generatedImage} alt="Generated by AI" className="max-w-full max-h-[512px] rounded-lg shadow-lg" />
        )}
      </div>
    </div>
  );
};

export default ImageGenerator;
